name: Publish Docker
on:
  push:
    branches:
      - develop
  schedule:
    - cron:  '0 0 * * FRI'      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        set -e
        git fetch --prune --shallow-since=$(date -I -d '-1 month')
        git remote add upstream https://github.com/gohugoio/hugo.git
        origin_tag=`git describe --abbrev=0`
        echo "origin tag: ${origin_tag}"
        upstream_tag=`git ls-remote --sort taggerdate --refs --tags upstream | tail -n 1 | sed 's/.*\///'`
        echo "upstream tag: ${upstream_tag}"
        if [ "$upstream_tag" -ne "$origin_tag" ]
        then
          git fetch upstream
          git push --tags

          git checkout tags/${upstream_tag}
          for commit in $(git log --reverse --author="lulu" --pretty=%H);
          do
              git cherry-pick $commit
          done
          git tag $upstream_tag
          git push --tags -f
        else
          echo "do nothing, has latest version ${origin_tag}"
        fi
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: l1990790120/hugo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true