name: Publish Docker
on:
  push:
    branches:
      - develop
  schedule:
    - cron:  '0 0 * * FRI'      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git remote add upstream https://github.com/gohugoio/hugo.git
        git fetch --unshallow --quiet
        origin_tag=`git describe --abbrev=0`
        echo "origin tag: ${origin_tag}"

        git fetch upstream --tags --quiet
        upstream_tag=`git ls-remote --exit-code --sort taggerdate --refs --tags upstream | tail -n 1 | sed 's/.*\///'`
        echo "upstream tag: ${upstream_tag}"

        if [ "$upstream_tag" != "$origin_tag" ]
        then
          git branch local ${upstream_tag}
          for commit in $(git log --reverse --author="lulu" --pretty=%H);
          do
              git cherry-pick $commit --strategy-option theirs
          done

          echo "did this happen?"
          git tag $upstream_tag
          git push --tags -f
        else
          echo "do nothing, has latest version ${origin_tag}"
        fi
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      if: contains(github.ref, 'refs/tags/v')
      with:
        name: l1990790120/hugo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tagging: true